version: 2
jobs:
  build:
    docker:
      - image: centos:7
    working_directory: /project
    steps:
      - checkout
      - run:
          name: install system prereqs
          command: yum -y install mock
      - run:
          name: create mock user
          command: useradd -G mock builder
      - run:
          name: change project permissions to mock user
          command: chown -R builder /project
      - run:
          name: mock build c7
          command: runuser -u builder ./mkimage-mock.sh c7
