version: 2
jobs:
  build:
    docker:
      - image: centos:7
    steps:
      - checkout
      - run:
          name: install system prereqs
          command: sudo yum -y install mock
      - run:
          name: mock build c7
          command: ./mkimage-mock.sh c7
