version: 2
jobs:
  build:
    docker:
      - image: centos:7
    working_directory: /project
    steps:
      - checkout
      - run:
          name: chroot build centos 7
          command: ./mkimage-chroot.sh -p yum -d centos-7
