version: 2
jobs:
  build:
    docker:
      - image: centos:7
    steps:
      - checkout
      - run:
          name: install system prereqs
          command: yum -y install mock
      - run:
          name: create mock user
          command: useradd -G mock builder
      - run:
          name: mock build c7
          command: runuser -u builder ./mkimage-mock.sh c7
