version: 2

references:
  rpm_cap_hack_steps: &rpm_cap_hack_steps
    steps:
      - checkout
      - run:
          name: centos 5 vault hack
          command: |
            bash -c 'v=$(rpm -q --qf "%{VERSION}" centos-release);case $v in 5) sed -i -e "/^mirrorlist.*/d" -e "s/^#baseurl/baseurl/g" -e "s/mirror/vault/g" -e "s@centos/\$releasever@5.11@g" /etc/yum.repos.d/CentOS-Base.repo ; rm -f /etc/yum.repos.d/libselinux.repo ;; esac'
      - run:
          name: installing capability hack prereqs
          command: yum -y install gcc libcap-devel || true
      - run:
          name: building capability hack
          command: bash -c 'mkdir -p hack_artifact/$plat && gcc -fPIC -Wall -shared -ohack_artifact/$plat/noop_cap_set_file.so hacks/cap_set_file.c'
      - persist_to_workspace:
          root: hack_artifact
          paths: .

jobs:
  capset-centos-5:
    docker:
      - image: centos:5
    working_directory: /project
    environment:
      plat: centos-5
    <<: *rpm_cap_hack_steps
  capset-centos-7:
    docker:
      - image: centos:7
    working_directory: /project
    environment:
      plat: centos-7
    <<: *rpm_cap_hack_steps
  capset-fedora-27:
    docker:
      - image: fedora:27
    working_directory: /project
    environment:
      plat: fedora-27
    <<: *rpm_cap_hack_steps
  build-centos-7:
    docker:
      - image: centos:7
    working_directory: /project
    environment:
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/LIBCAP_HACKS
      - run:
          name: local capability hack install
          command: install -m755 "/tmp/LIBCAP_HACKS/centos-7/noop_cap_set_file.so" "/usr/local/lib64/noop_cap_set_file.so"
      - run:
          name: install docker prereqs
          command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo && yum -y install docker-ce && yum -y install epel-release && yum -y install debootstrap perl
      - setup_remote_docker
      - run:
          name: docker login docker.io
          command: |
              docker login -u $DOCKER_USER -p $DOCKER_PASS docker.io
      - run:
          name: chroot build fedora 27
          command: env DNAME=docker.io/redjays/fedora ./mkimage-chroot.sh -p yum -d fedora-27 -c
      - run:
          name: chroot build centos 5
          command: env DNAME=docker.io/redjays/c5 ./mkimage-chroot.sh -p yum -d centos-5 -c
      - run:
          name: chroot build centos 7
          command: env DNAME=docker.io/redjays/c7 ./mkimage-chroot.sh -p yum -d centos-7 -c
      - run:
          name: chroot build ubuntu xenial 7
          command: cat /proc/1/environ && env TMPDIR=/var/tmp DNAME=docker.io/redjays/xenial ./mkimage-chroot.sh -p apt -d ubuntu-xenial
      - run:
          name: docker build c7:docker-ce
          command: cd docker/c7/docker-ce && docker build -t docker.io/redjays/c7:docker-ce . && docker push docker.io/redjays/c7:docker-ce

workflows:
  version: 2
  build:
    jobs:
      - capset-centos-5
      - capset-centos-7
      - capset-fedora-27
      - build-centos-7:
          requires:
              - capset-centos-7
              - capset-centos-5
              - capset-fedora-27
